# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_name', models.CharField(max_length=40)),
                ('contact_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(help_text='Only input numbers, No Dash Marks', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventsCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_information', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('room_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_title', models.CharField(max_length=20)),
                ('map_id', models.IntegerField(default=0, unique=True)),
                ('open_24_hours_for_students', models.BooleanField(default=False)),
                ('monday_open', models.TimeField()),
                ('monday_close', models.TimeField()),
                ('tuesday_open', models.TimeField()),
                ('tuesday_close', models.TimeField()),
                ('wednesday_open', models.TimeField()),
                ('wednesday_close', models.TimeField()),
                ('thursday_open', models.TimeField()),
                ('thursday_close', models.TimeField()),
                ('friday_open', models.TimeField()),
                ('friday_close', models.TimeField()),
                ('saturday_open', models.TimeField()),
                ('saturday_close', models.TimeField()),
                ('sunday_open', models.TimeField()),
                ('sunday_close', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='eventscalendar',
            name='location_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Location'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Location'),
        ),
        migrations.AddField(
            model_name='calendarexception',
            name='event_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='display.EventsCalendar'),
        ),
        migrations.AddField(
            model_name='calendarexception',
            name='location_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Location'),
        ),
    ]
